# Generated by Django 6.0 on 2025-12-27 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, help_text='Who was this job for?', max_length=200)),
                ('description', models.TextField(help_text='Details about the project specs.')),
                ('print_method', models.CharField(blank=True, max_length=100)),
                ('material_used', models.CharField(blank=True, max_length=100)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('finishing', models.CharField(blank=True, help_text='e.g., Matte Lamination, Spot UV, Die Cut', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page gallery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False, help_text='Use this image as the thumbnail/cover for the project.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.project')),
            ],
            options={
                'ordering': ['-is_cover', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, help_text="Icon for the service (e.g., specific to 'Design' or 'Large Format').", upload_to='services/icons/')),
                ('cover_image', models.ImageField(blank=True, help_text='Main background image for this service page.', upload_to='services/covers/')),
                ('description', models.TextField(blank=True, help_text='Short intro about this service.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank if this is a Main Service (e.g., Garment Printing). Select a parent if this is a sub-category (e.g., T-Shirts).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='gallery.servicecategory')),
            ],
            options={
                'verbose_name': 'Service / Category',
                'verbose_name_plural': 'Services / Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='gallery.servicecategory'),
        ),
    ]
