# Generated by Django 6.0 on 2025-12-27 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading. Restricted to 50 characters.', max_length=50)),
                ('subtitle', models.CharField(blank=True, help_text='Sub-heading. Restricted to 100 characters.', max_length=100)),
                ('image', models.ImageField(help_text='High-resolution banner image (e.g., 1920x600).', upload_to='banners/')),
                ('cta_text', models.CharField(blank=True, help_text="Text for the button (e.g., 'View Work').", max_length=20)),
                ('cta_link', models.URLField(blank=True, help_text='Full URL where the banner button should link.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_interest', models.CharField(blank=True, help_text='Which service are they interested in?', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Integrity', 'Quality'", max_length=50)),
                ('description', models.TextField(help_text='Short explanation of this value (Max 300 chars).', validators=[django.core.validators.MaxLengthValidator(300)])),
                ('icon', models.ImageField(help_text='Icon representing the value.', upload_to='core_values/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., '20 Years Experience', 'Eco-Friendly Inks'", max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='why_choose_us/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order'],
            },
        ),
    ]
