# Generated by Django 6.0 on 2026-08-09 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_banner_cta_link_internal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="cta_link",
            field=models.CharField(
                blank=True,
                default="/",
                help_text="Internal URL path (e.g., '/contact'). Leave blank for homepage.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CTA link must be an internal path starting with '/'.",
                        regex="^/[^\\\\s]*$",
                    )
                ],
            ),
        ),
    ]
